export { default as cButtonFooter } from './components/cButtonFooter';
export { default as cItem } from './components/cItem';
export { default as cConfirm } from './components/cConfirm';
export { default as cHeaderBack }from './components/cHeaderBack';
export { default as cButton } from './components/cButton';
export { default as cInputPassword } from './components/cInputPassword';
export { default as cInput } from './components/cInput';
export { default as cSwitch } from './components/cSwitch';
export { default as cLoading } from './components/cLoading';
export { default as cPassword } from './components/cPassword';
export { default as cBar } from './components/cBar';
export { default as cCircle } from './components/cCircle';
export { default as cScrollAble } from './components/cScrollAble';
export { default as cScrollX } from './components/cScrollX';
export { default as cSlide } from './components/cSlide';
// export { default as cSwiper } from './components/cSwiper'; //后面再更新
export { default as cTabs } from './components/cTabs';
export { default as cTimeCircle } from './components/cTimeCircle';
export { default as cTimeCount } from './components/cTimeCount';
export { default as cToast } from './components/cToast';